### ISSUE TITLE
Executing actions twice

### ISSUE THREAD

**Issue by sdjukic** [cuny-nytech/jan-teamC#10]
Now I remembered why executing actions twice is a problem. When trying to create new user application is trying to save the same user twice, and it breaks the requirement of user name being unique.
(0.5ms)  begin transaction
(0.5ms)  begin transaction
User Exists (0.3ms)  SELECT  1 AS one FROM "users" WHERE LOWER("users"."username") = LOWER('first_user') LIMIT 1
User Exists (0.3ms)  SELECT  1 AS one FROM "users" WHERE LOWER("users"."username") = LOWER('first_user') LIMIT 1
SQL (0.2ms)  INSERT INTO "users" ... abbreviated
SQL (0.2ms)  INSERT INTO "users" ...
(144.9ms)  commit transaction
(144.9ms)  commit transaction
Completed 406 Not Acceptable in 276ms
Completed 406 Not Acceptable in 276ms

Craziest thing is that user is created and saved (on the first try), but since we are breaking the requirement of uniqueness when we execute action the second time exception is thrown and it breaks the application.

**Comment by afeld** [comment]
Have you tried removing/disabling Turbolinks?

**Comment by sdjukic** [comment]
Removed them from Gemfile, application.js and in my application layout I changed the line to
<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => **false** %>
Not sure if there is any other place to look for them.

**Comment by afeld** [comment]
And that didn't work? Sounds like Turbolinks probably aren't the issue then.

**Comment by sdjukic** [comment]
I tracked it down to panda gem. After I removed it from Gemfile and commented out its script in initialization problem disappeared.
Thanks for the tip on moving between commits and `git log -p` helped tracked changes.
